CREATE DATABASE IF NOT EXISTS skyd_db;

USE skyd_db;

CREATE TABLE IF NOT EXISTS USER_TABLE(
  userId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  imageURL VARCHAR(255) DEFAULT NULL,
  createdBy BIGINT UNSIGNED DEFAULT NULL,
  deleted BOOLEAN NOT NULL DEFAULT 0,
  deleteBy BIGINT UNSIGNED DEFAULT NULL,
  password VARCHAR(255) DEFAULT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  userType INT NOT NULL DEFAULT 0,
  PRIMARY KEY (userId),
  CONSTRAINT UQUserEmail UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS documentTable (
  fileId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ownerId BIGINT UNSIGNED NOT NULL,
  label VARCHAR(255) DEFAULT NULL,
  fileURL VARCHAR(255) DEFAULT NULL,
  deleted BOOLEAN NOT NULL DEFAULT 0,
  deleteBy BIGINT UNSIGNED DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fileId)
);

CREATE TABLE IF NOT EXISTS groupRegisterTable (
  groupId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  groupName VARCHAR(255) NOT NULL,
  adminId BIGINT UNSIGNED NOT NULL,
  description VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (adminId) REFERENCES USER_TABLE(userId)
);

CREATE TABLE IF NOT EXISTS groupMemberTable (
  memberId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  groupId BIGINT NOT NULL,
  userId BIGINT UNSIGNED NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (groupId) REFERENCES GroupRegisterTable(groupId),
  FOREIGN KEY (userId) REFERENCES USER_TABLE(userId)
);

CREATE TABLE IF NOT EXISTS groupChatTable (
  chatId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  senderId BIGINT NOT NULL,
  message TEXT NOT NULL,
  groupId BIGINT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (senderId) REFERENCES groupMemberTable(memberId)
);

